### ISSUE TITLE
Voyant and/or reproducibility

### ISSUE THREAD

**Issue by dhicks** [cpence/text-mining-workshop#1]
I'm not familiar with Voyant, but it looks like a GUI-based tool.  I can understand the appeal of using GUI-based tools with people who don't have any experience programming (or, indeed, running commands in a terminal window!).  

But the reproducible research community makes what I think is a very strong case for scripting-based tools:  briefly, the entire analysis can be reproduced / should be reproducible given just the data and script files and without human intervention.  An analysis that can be reproduced in this sense can more-or-less easily be unpacked by interested outsiders who are trying to understand the methods used, checked for errors, modified to check for stability, extended or modified in downstream research, and so on.  

I think a brief introductory workshop on text mining in DH is a nice occasion to at least raise these issues.  [Here](http://kieranhealy.org/publications/plain-person-text/) is a nice Kieran Healy paper that does that.

**Comment by cpence** [comment]
Great idea! I also had forgotten to include a big warning about saving your work and exporting in portable (CSV, TXT) data formats, so this was a perfect occasion to do that as well. Thanks!
